Description: Opsworks Stack

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  PrivateSubnet:
    Type: String
  VpcId:
    Type: String
  MongoSecurityGroup:
    Type: String
  EnvironmentName:
    Type: String
  zipFileS3:
    Type: String

Resources:

  defaultRole:
      Type: AWS::IAM::Role
      Properties:
          AssumeRolePolicyDocument:
              Statement:
                - Effect: Allow
                  Principal:
                      Service:
                        - ec2.amazonaws.com
                  Action:
                    - sts:AssumeRole

  defaultInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      DependsOn: bucketRole
      Properties:
          Path: /
          Roles:
            - !Ref bucketRole


  OpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties:
      Name: !Ref EnvironmentName
      ServiceRoleArn: !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':role/aws-opsworks-service-role']]
      DefaultInstanceProfileArn: !Ref defaultInstanceProfile
      DefaultSshKeyName: !Ref 'KeyName'
      DefaultOs: Ubuntu 16.04 LTS
      DefaultRootDeviceType: ebs
      VpcId: !Ref VpcId
      DefaultSubnetId: !Ref PrivateSubnet
      UseCustomCookbooks: true
      UseOpsworksSecurityGroups: true
      CustomCookbooksSource:
        Type: S3
        Url: !Ref zipFileS3
      ConfigurationManager:
        Name: Chef
        Version: '12'
      CustomJson: !Sub |
          {
            "master_node": "master1"
          }

  Mongo:
    Type: AWS::OpsWorks::Layer
    Properties:
      AutoAssignElasticIps: true
      AutoAssignPublicIps:  true
      CustomRecipes:
        Setup:
          - mongodb3::default
        Configure:
          - mongodb3::configure
      StackId: !Ref 'OpsWorksStack'
      Name: Mongo
      Type: custom
      Shortname: mongo
      VolumeConfigurations:
        - MountPoint: /data
          NumberOfDisks: 1
          Size: 1000
          VolumeType: gp2
          Encrypted: true
      EnableAutoHealing: 'false'
      CustomSecurityGroupIds:
      - !Ref 'MongoSecurityGroup'
