---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/integration/data_bags
  require_chef_omnibus: 12.1.2

platforms:
  - name: ubuntu-16.04 # XXX(theckman): EOL 2021/04
    driver:
      box: opscode_ubuntu-16.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-16.04_chef-provisionerless.box
  - name: ubuntu-14.04 # XXX(theckman): EOL 2019/04
    driver:
      box: opscode_ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  - name: ubuntu-12.04 # XXX(theckman): EOL 2017/04
    driver:
      box: opscode_ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  - name: centos-7.x # XXX(theckman): EOL 2024/06/30
    driver:
      box: opscode_centos-7.2
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.2_chef-provisionerless.box
  - name: centos-6.x # XXX(theckman): EOL 2020/11/30
    driver:
      box: opscode_centos-6.8
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.8_chef-provisionerless.box
  - name: centos-5.x # XXX(theckman): EOL 2017/03/31
    # XXX(theckman): CentOS 5.11 in a VirtualBox instance enters Guru Meditation mode :(
    # Known Issue: https://github.com/chef/bento/blob/master/CHANGELOG.md#230-2016-09-30
    driver:
      box: opscode_centos-5.10
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10_chef-provisionerless.box

suites:
- name: lwrp
  run_list:
  - recipe[user_test::lwrp]
  attributes: {}
- name: data_bag
  run_list:
  - recipe[user::data_bag]
  attributes:
    users:
    - hsolo
    - lando
    - luke.skywalker
- name: data_bag_no_users
  run_list:
  - recipe[user::data_bag]
  attributes: {}
- name: home_dir_mode
  run_list:
  - recipe[user_test::lwrp]
  attributes:
    user:
      home_dir_mode: "0700"
